### ISSUE TITLE
如何单独应用deepsort_mars.om

### ISSUE THREAD

**Issue by Leon16226** [lenLRX/Atlas_ACL_E2E_Demo#11]
你好，首先感谢你的项目
我现在想把在200dk上，
在我自己的yolov4.om输出后面接上，deepsort_mars.om进行追踪。

使用mindstudio查看deepsort_mars.om结构，
得知其输入为[16, 128, 64, 3]。

我有以下疑问：
1. [16, 128, 64, 3]的输入代表的意义
2. yolov4的detct的输出怎么转化为deepsort_mars.om的输入
3. 我使用的是python，对于这个转化过程可以参考你的那一些代码？

以上，再次感谢！

**Comment by lenLRX** [comment]
16，是我设置的batchsize 我觉得这样会性能好点。
后面3个维度是输入图片的shape

**Comment by lenLRX** [comment]
deepsort的输入是检测框扣出来的图片。
所以要
1.扣图
2.resize

**Comment by lenLRX** [comment]
整体流程参考deep_sort_stream.cpp
我不觉得这个用Python写会好写。。

**Comment by Leon16226** [comment]
看不懂deep_sort_stream.cpp
可以参考deep_sort原工程的推理流程马？

**Comment by lenLRX** [comment]
> 看不懂deep_sort_stream.cpp
> 可以参考deep_sort原工程的推理流程马？

可以，deep_sort_stream.cpp就是参考原来的工程写的。
虽然我觉得原来的工程也不是那么好理解
