### ISSUE TITLE
编译环境

### ISSUE THREAD

**Issue by unique-yaoli** [lenLRX/Atlas_ACL_E2E_Demo#12]
大佬 你这个工程的编译环境是直接在200DK上面编的吧，有没有x86下交叉编译的版本呢

**Comment by lenLRX** [comment]
> 大佬 你这个工程的编译环境是直接在200DK上面编的吧，有没有x86下交叉编译的版本呢

没有，我觉得这样比较方便。
我比较好奇你为什么想要在X86上交叉编译，是出于什么考虑？

**Comment by unique-yaoli** [comment]
> > 大佬 你这个工程的编译环境是直接在200DK上面编的吧，有没有x86下交叉编译的版本呢
> 
> 没有，我觉得这样比较方便。
> 我比较好奇你为什么想要在X86上交叉编译，是出于什么考虑？

DK上面资源有限 所以就只做了运行环境。

**Comment by lenLRX** [comment]
> > > 大佬 你这个工程的编译环境是直接在200DK上面编的吧，有没有x86下交叉编译的版本呢
> > 
> > 没有，我觉得这样比较方便。
> > 我比较好奇你为什么想要在X86上交叉编译，是出于什么考虑？
> 
> DK上面资源有限 所以就只做了运行环境。

DK上不用安装CANN的“开发环境”，那个确实很大。
但是我的demo只需要一小部分，按照我的文档中的指导配置环境，空间是足够的。
不需要安装官方的“开发环境”
