### ISSUE TITLE
感谢大神开源，请问一下rtsp或者rtmp推流需要修改配置文件哪个位置呢？

### ISSUE THREAD

**Issue by LDS13590023880** [lenLRX/Atlas_ACL_E2E_Demo#13]
请问一下rtsp或者rtmp推流需要修改配置文件哪个位置呢？

**Comment by lenLRX** [comment]
推流的话，你首先需要一个流媒体服务器。比如我在文档中写的nginx，或者你有其他的也可以。
然后输出地址"dst"写你对应输出流的地址就可以了。

https://github.com/lenLRX/Atlas_ACL_E2E_Demo/blob/master/run.md
![image](https://user-images.githubusercontent.com/9995828/134686257-5f976063-be12-4028-bba1-78979683a5a3.png)

**Comment by LDS13590023880** [comment]
哦哦，明白了，感谢大神指导

**Comment by LDS13590023880** [comment]
![image](https://user-images.githubusercontent.com/30891230/134690966-7ba6ab65-3be1-4686-a8e5-852b223bb538.png)
![image](https://user-images.githubusercontent.com/30891230/134691179-67b284fd-9fd3-48d5-8589-93b8fb1465db.png)
请问一下是这样子配置吗

**Comment by lenLRX** [comment]
> ![image](https://user-images.githubusercontent.com/30891230/134690966-7ba6ab65-3be1-4686-a8e5-852b223bb538.png)
> ![image](https://user-images.githubusercontent.com/30891230/134691179-67b284fd-9fd3-48d5-8589-93b8fb1465db.png)
> 请问一下是这样子配置吗

"dst"应该要用rtmp，因为nginx似乎不支持rtsp，只支持rtmp，最后最好也加上一个流的名字，例子：
“dst”: "rtmp://127.0.0.1/myapp/test1"

另外需要确认一下nginx启动没有，不确定的话可以使用一下命令启动一下
`
.  /usr/local/nginx/sbin/nginx
`

**Comment by LDS13590023880** [comment]
跑通了。感谢
