### ISSUE TITLE
量化过程中出现报错

### ISSUE THREAD

**Issue by YuxiangJohn** [lenLRX/Atlas_ACL_E2E_Demo#14]
![image](https://user-images.githubusercontent.com/26529718/135045916-59df554e-f7e4-4847-816b-ab942122b90e.png)
yolov3进行量化，amct报错如上，看文档说是caffe错误，但是caffe没有报错。不知道是否有人踩过坑

**Comment by lenLRX** [comment]
> ![image](https://user-images.githubusercontent.com/26529718/135045916-59df554e-f7e4-4847-816b-ab942122b90e.png)
> yolov3进行量化，amct报错如上，看文档说是caffe错误，但是caffe没有报错。不知道是否有人踩过坑

你这个caffe量化是按照我的知乎文章搞得吗。使用我打过patch的caffe版本

如果是的话，我回头再测试一下。

**Comment by YuxiangJohn** [comment]
> > ![image](https://user-images.githubusercontent.com/26529718/135045916-59df554e-f7e4-4847-816b-ab942122b90e.png)
> > yolov3进行量化，amct报错如上，看文档说是caffe错误，但是caffe没有报错。不知道是否有人踩过坑
> 
> 你这个caffe量化是按照我的知乎文章搞得吗。使用我打过patch的caffe版本
> 
> 如果是的话，我回头再测试一下。

我使用的是GitHub quant.md里的介绍搞的，使用的是你提供的caffe-ascend-amct，按照你的cann docker构建的image进行操作。

**Comment by YuxiangJohn** [comment]
> > ![image](https://user-images.githubusercontent.com/26529718/135045916-59df554e-f7e4-4847-816b-ab942122b90e.png)
> > yolov3进行量化，amct报错如上，看文档说是caffe错误，但是caffe没有报错。不知道是否有人踩过坑
> 
> 你这个caffe量化是按照我的知乎文章搞得吗。使用我打过patch的caffe版本
> 
> 如果是的话，我回头再测试一下。

幸苦大佬再看看，大佬的工作很全面，值得我们学习~

**Comment by lenLRX** [comment]
> > > ![image](https://user-images.githubusercontent.com/26529718/135045916-59df554e-f7e4-4847-816b-ab942122b90e.png)
> > > yolov3进行量化，amct报错如上，看文档说是caffe错误，但是caffe没有报错。不知道是否有人踩过坑
> > 
> > 你这个caffe量化是按照我的知乎文章搞得吗。使用我打过patch的caffe版本
> > 
> > 如果是的话，我回头再测试一下。
> 
> 幸苦大佬再看看，大佬的工作很全面，值得我们学习~

好，我抽空再测试一下。不排除是新版本有更新出啥问题了orz

**Comment by YuxiangJohn** [comment]
> > > > ![image](https://user-images.githubusercontent.com/26529718/135045916-59df554e-f7e4-4847-816b-ab942122b90e.png)
> > > > yolov3进行量化，amct报错如上，看文档说是caffe错误，但是caffe没有报错。不知道是否有人踩过坑
> > > 
> > > 
> > > 你这个caffe量化是按照我的知乎文章搞得吗。使用我打过patch的caffe版本
> > > 如果是的话，我回头再测试一下。
> > 
> > 
> > 幸苦大佬再看看，大佬的工作很全面，值得我们学习~
> 
> 好，我抽空再测试一下。不排除是新版本有更新出啥问题了orz

大佬有空可以搞个简易的onnx量化过程，官方文档不太友好，sample也没有，让我们这些非华为的人很难搞，唉。。。
华为官方啥时候出一些比较完整好用的quant例子。。。大佬可以催一下哈哈~~~

**Comment by YuxiangJohn** [comment]
已解决，通过注释代码运行发现由于视频文件的原因导致，打扰了哈哈哈。。

**Comment by lenLRX** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/26529718/135045916-59df554e-f7e4-4847-816b-ab942122b90e.png)
> > > > > yolov3进行量化，amct报错如上，看文档说是caffe错误，但是caffe没有报错。不知道是否有人踩过坑
> > > > 
> > > > 
> > > > 你这个caffe量化是按照我的知乎文章搞得吗。使用我打过patch的caffe版本
> > > > 如果是的话，我回头再测试一下。
> > > 
> > > 
> > > 幸苦大佬再看看，大佬的工作很全面，值得我们学习~
> > 
> > 
> > 好，我抽空再测试一下。不排除是新版本有更新出啥问题了orz
> 
> 大佬有空可以搞个简易的onnx量化过程，官方文档不太友好，sample也没有，让我们这些非华为的人很难搞，唉。。。 华为官方啥时候出一些比较完整好用的quant例子。。。大佬可以催一下哈哈~~~

onnx量化的文档我之后搞一下。官方的sample应该还是有的，不过估计也是不太友好的。。
https://github.com/Ascend/samples/tree/master/python/level1_single_api/9_amct/amct_onnx

你让我催，我催有啥用呀ORZ。。
