### ISSUE TITLE
请问一下这个问题您遇过吗

### ISSUE THREAD

**Issue by LDS13590023880** [lenLRX/Atlas_ACL_E2E_Demo#15]
![ae2a18f0b2f9070546c2e6be2778d02](https://user-images.githubusercontent.com/30891230/136126752-358d3ab7-58a5-449f-b836-db8cf83acb55.jpg)
是需要安装ffmpeg吗

**Comment by lenLRX** [comment]
![image](https://user-images.githubusercontent.com/9995828/136128199-e18e673f-5ff1-4df5-a4d6-0a10667fda20.png)
这里是解析帧率出了问题，解析不出来帧率。我不是很精通流媒体协议，不清楚什么情况下没有帧率。
建议你用ffprobe检查一下这个流,把得到的信息贴出来
ffprobe安装方法: apt install ffmpeg
