### ISSUE TITLE
Atlas 200DK 编译

### ISSUE THREAD

**Issue by Yuanye-F** [lenLRX/Atlas_ACL_E2E_Demo#17]
[100%] Linking CXX executable benchmark_demo
/usr/bin/ld: warning: libdevmm.so, needed by /usr/local/Ascend/acllib/lib64/libruntime.so, not found (try using -rpath or -rpath-link)

**Comment by lenLRX** [comment]
最后编译能成功吗？

你的软件版本是什么，驱动和CANN的版本

**Comment by Yuanye-F** [comment]
没有编译成功

acllib为20.0版本，驱动版本21.0.2

**Comment by Yuanye-F** [comment]
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- ATLAS_DEVICE not set, detected device type: Atlas200DK
-- build with libmedia TRUE
-- Found Freetype: /usr/lib/aarch64-linux-gnu/libfreetype.so (found version "2.8.1")
-- set ACL_PATH: /usr/local/Ascend/acllib
-- Configuring done
-- Generating done
-- Build files have been written to: /home/HwHiAiUser/work_zp/code/Atlas_ACL_E2E_Demo/build
Scanning dependencies of target acl_demo
[  8%] Building CXX object CMakeFiles/acl_demo.dir/src/dvpp_decoder.cpp.o
[  8%] Building CXX object CMakeFiles/acl_demo.dir/src/ffmpeg_output.cpp.o
[ 13%] Building CXX object CMakeFiles/acl_demo.dir/src/acl_model.cpp.o
[ 17%] Building CXX object CMakeFiles/acl_demo.dir/src/ffmpeg_input.cpp.o
/home/HwHiAiUser/work_zp/code/Atlas_ACL_E2E_Demo/src/ffmpeg_input.cpp: In member function ‘int FFMPEGInput::Init(const string&)’:
/home/HwHiAiUser/work_zp/code/Atlas_ACL_E2E_Demo/src/ffmpeg_input.cpp:40:28: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
     if (av_fc->streams[i]->codec->codec_type == AVMEDIA_TYPE_VIDEO) {
                            ^~~~~
In file included from /home/HwHiAiUser/work_zp/code/Atlas_ACL_E2E_Demo/src/ffmpeg_input.h:6:
,
                 from /home/HwHiAiUser/work_zp/code/Atlas_ACL_E2E_Demo/src/ffmpeg_input.cpp:
:
/usr/local/ffmpeg-3.1.11/include/libavformat/avformat.h:880:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
/home/HwHiAiUser/work_zp/code/Atlas_ACL_E2E_Demo/src/ffmpeg_input.cpp:40:28: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
     if (av_fc->streams[i]->codec->codec_type == AVMEDIA_TYPE_VIDEO) {
                            ^~~~~
In file included from /home/HwHiAiUser/work_zp/code/Atlas_ACL_E2E_Demo/src/ffmpeg_input.h:6:
,
                 from /home/HwHiAiUser/work_zp/code/Atlas_ACL_E2E_Demo/src/ffmpeg_input.cpp:
:
/usr/local/ffmpeg-3.1.11/include/libavformat/avformat.h:880:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
/home/HwHiAiUser/work_zp/code/Atlas_ACL_E2E_Demo/src/ffmpeg_input.cpp:40:28: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
     if (av_fc->streams[i]->codec->codec_type == AVMEDIA_TYPE_VIDEO) {
                            ^~~~~
In file included from /home/HwHiAiUser/work_zp/code/Atlas_ACL_E2E_Demo/src/ffmpeg_input.h:6:
,
                 from /home/HwHiAiUser/work_zp/code/Atlas_ACL_E2E_Demo/src/ffmpeg_input.cpp:
:
/usr/local/ffmpeg-3.1.11/include/libavformat/avformat.h:880:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
/home/HwHiAiUser/work_zp/code/Atlas_ACL_E2E_Demo/src/ffmpeg_input.cpp:51:41: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
   av_cc = av_fc->streams[video_stream]->codec;
                                         ^~~~~
In file included from /home/HwHiAiUser/work_zp/code/Atlas_ACL_E2E_Demo/src/ffmpeg_input.h:6:
,
                 from /home/HwHiAiUser/work_zp/code/Atlas_ACL_E2E_Demo/src/ffmpeg_input.cpp:
:
/usr/local/ffmpeg-3.1.11/include/libavformat/avformat.h:880:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
/home/HwHiAiUser/work_zp/code/Atlas_ACL_E2E_Demo/src/ffmpeg_input.cpp:51:41: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
   av_cc = av_fc->streams[video_stream]->codec;
                                         ^~~~~
In file included from /home/HwHiAiUser/work_zp/code/Atlas_ACL_E2E_Demo/src/ffmpeg_input.h:6:
,
                 from /home/HwHiAiUser/work_zp/code/Atlas_ACL_E2E_Demo/src/ffmpeg_input.cpp:
:
/usr/local/ffmpeg-3.1.11/include/libavformat/avformat.h:880:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
/home/HwHiAiUser/work_zp/code/Atlas_ACL_E2E_Demo/src/ffmpeg_input.cpp:51:41: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
   av_cc = av_fc->streams[video_stream]->codec;
                                         ^~~~~
In file included from /home/HwHiAiUser/work_zp/code/Atlas_ACL_E2E_Demo/src/ffmpeg_input.h:6:
,
                 from /home/HwHiAiUser/work_zp/code/Atlas_ACL_E2E_Demo/src/ffmpeg_input.cpp:
:
/usr/local/ffmpeg-3.1.11/include/libavformat/avformat.h:880:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
[ 21%] Building CXX object CMakeFiles/acl_demo.dir/src/vpc_resize.cpp.o
[ 26%] Building CXX object CMakeFiles/acl_demo.dir/src/vpc_batch_crop.cpp.o
[ 30%] Building CXX object CMakeFiles/acl_demo.dir/src/jpeg_encode.cpp.o
[ 34%] Building CXX object CMakeFiles/acl_demo.dir/src/dvpp_encoder.cpp.o
[ 39%] Building CXX object CMakeFiles/acl_demo.dir/src/freetype_helper.cpp.o
[ 43%] Building CXX object CMakeFiles/acl_demo.dir/src/camera_input.cpp.o
[ 47%] Building CXX object CMakeFiles/acl_demo.dir/src/app_profiler.cpp.o
[ 52%] Building CXX object CMakeFiles/acl_demo.dir/src/yolov3_stream.cpp.o
[ 56%] Building CXX object CMakeFiles/acl_demo.dir/src/yolov4_stream.cpp.o
In file included from /usr/include/python3.6/numpy/ndarraytypes.h:1809:0,
                 from /usr/include/python3.6/numpy/ndarrayobject.h:18,
                 from /home/HwHiAiUser/work_zp/code/Atlas_ACL_E2E_Demo/src/yolov4_stream.cpp:1:
/usr/include/python3.6/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^~~~~~~
[ 60%] Building CXX object CMakeFiles/acl_demo.dir/src/yolov5_stream.cpp.o
In file included from /usr/include/python3.6/numpy/ndarraytypes.h:1809:0,
                 from /usr/include/python3.6/numpy/ndarrayobject.h:18,
                 from /home/HwHiAiUser/work_zp/code/Atlas_ACL_E2E_Demo/src/yolov5_stream.cpp:1:
/usr/include/python3.6/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^~~~~~~
[ 65%] Building CXX object CMakeFiles/acl_demo.dir/src/signal_handler.cpp.o
[ 69%] Building CXX object CMakeFiles/acl_demo.dir/src/deep_sort_stream.cpp.o
In file included from /usr/include/python3.6/numpy/ndarraytypes.h:1809:0,
                 from /usr/include/python3.6/numpy/ndarrayobject.h:18,
                 from /home/HwHiAiUser/work_zp/code/Atlas_ACL_E2E_Demo/src/deep_sort_stream.cpp:1:
/usr/include/python3.6/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^~~~~~~
[ 73%] Building CXX object CMakeFiles/acl_demo.dir/src/stream_factory.cpp.o
[ 78%] Building CXX object CMakeFiles/acl_demo.dir/src/device_manager.cpp.o
[ 82%] Linking CXX shared library libacl_demo.so
[ 82%] Built target acl_demo
Scanning dependencies of target benchmark_demo
Scanning dependencies of target acl_demo_app
[ 91%] Building CXX object CMakeFiles/acl_demo_app.dir/src/acl_demo_app.cpp.o
[ 91%] Building CXX object CMakeFiles/benchmark_demo.dir/src/benchmark_demo.cpp.o
[ 95%] Linking CXX executable acl_demo_app
[100%] Linking CXX executable benchmark_demo
/usr/bin/ld: warning: libdevmm.so, needed by /usr/local/Ascend/acllib/lib64/libruntime.so, not found (try using -rpath or -rpath-link)
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvIpcCloseMemHandle'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvStreamIdAlloc'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvCommandOccupy'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvIpcSetPidMemHandle'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvMemFreeDvppManaged'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvReportGet'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvMemAdvise'
/usr/local/Ascend/acllib/lib64/libascendcl.so: undefined reference to `Msprof::Engine::UnInit(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvTaskPoolIdFree'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvMemAllocHost'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvEventIdFree'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvReportPollWait'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvDeviceGetCount'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `halSqCommandSend'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvMemAllocManaged'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvMemFreeHugePageManaged'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvIpcOpenMemHandle'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `halCqReportRelease'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvIpcDestroyMemHandle'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvTaskPoolIdAlloc'
/usr/local/Ascend/acllib/lib64/libascendcl.so: undefined reference to `ProfMgrGetConf(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ProfMgrConf*)'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvNotifyIdFree'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `halMemAllocDevice'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvIpcCreateMemHandle'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvModelIdFree'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `Msprof::Engine::RegisterEngine(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Msprof::Engine::EngineIntf const*)'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvEventIdAlloc'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `halSqCommandOccupy'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvModelIdAlloc'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvNotifyIdAlloc'
/usr/local/Ascend/acllib/lib64/libascendcl.so: undefined reference to `Msprof::Engine::Init(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Msprof::Engine::EngineIntf const*)'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvMemAllocHugePageManaged'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvReportIrqWait'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `halMemFreeDevice'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvMemFreeHost'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvReportRelease'
/usr/local/Ascend/acllib/lib64/libascendcl.so: undefined reference to `ProfMgrStop(void*)'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvMemAllocForDvppManaged'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvStreamIdFree'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvMemFreeManaged'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvCommandSend'
/usr/local/Ascend/acllib/lib64/libascendcl.so: undefined reference to `ProfMgrStartUp(ProfMgrCfg const*)'
collect2: error: ld returned 1 exit status
CMakeFiles/acl_demo_app.dir/build.make:99: recipe for target 'acl_demo_app' failed
make[2]: *** [acl_demo_app] Error 1
CMakeFiles/Makefile2:141: recipe for target 'CMakeFiles/acl_demo_app.dir/all' failed
make[1]: *** [CMakeFiles/acl_demo_app.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: warning: libdevmm.so, needed by /usr/local/Ascend/acllib/lib64/libruntime.so, not found (try using -rpath or -rpath-link)
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvIpcCloseMemHandle'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvStreamIdAlloc'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvCommandOccupy'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvIpcSetPidMemHandle'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvMemFreeDvppManaged'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvReportGet'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvMemAdvise'
/usr/local/Ascend/acllib/lib64/libascendcl.so: undefined reference to `Msprof::Engine::UnInit(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvTaskPoolIdFree'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvMemAllocHost'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvEventIdFree'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvReportPollWait'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvDeviceGetCount'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `halSqCommandSend'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvMemAllocManaged'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvMemFreeHugePageManaged'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvIpcOpenMemHandle'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `halCqReportRelease'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvIpcDestroyMemHandle'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvTaskPoolIdAlloc'
/usr/local/Ascend/acllib/lib64/libascendcl.so: undefined reference to `ProfMgrGetConf(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ProfMgrConf*)'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvNotifyIdFree'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `halMemAllocDevice'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvIpcCreateMemHandle'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvModelIdFree'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `Msprof::Engine::RegisterEngine(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Msprof::Engine::EngineIntf const*)'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvEventIdAlloc'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `halSqCommandOccupy'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvModelIdAlloc'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvNotifyIdAlloc'
/usr/local/Ascend/acllib/lib64/libascendcl.so: undefined reference to `Msprof::Engine::Init(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Msprof::Engine::EngineIntf const*)'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvMemAllocHugePageManaged'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvReportIrqWait'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `halMemFreeDevice'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvMemFreeHost'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvReportRelease'
/usr/local/Ascend/acllib/lib64/libascendcl.so: undefined reference to `ProfMgrStop(void*)'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvMemAllocForDvppManaged'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvStreamIdFree'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvMemFreeManaged'
/usr/local/Ascend/acllib/lib64/libruntime.so: undefined reference to `drvCommandSend'
/usr/local/Ascend/acllib/lib64/libascendcl.so: undefined reference to `ProfMgrStartUp(ProfMgrCfg const*)'
collect2: error: ld returned 1 exit status
CMakeFiles/benchmark_demo.dir/build.make:99: recipe for target 'benchmark_demo' failed
make[2]: *** [benchmark_demo] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/benchmark_demo.dir/all' failed
make[1]: *** [CMakeFiles/benchmark_demo.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by lenLRX** [comment]
我觉得问题可能是你的驱动版本和acllib版本不对应。


另外20.0也比较老了，建议使用最新的软件版本

**Comment by Yuanye-F** [comment]
好的，尝试一下其他版本。

**Comment by Yuanye-F** [comment]
解决了，升级CANN版本到5.0.5.alpha001后编译成功
