### ISSUE TITLE
yolov5s转换om出错

### ISSUE THREAD

**Issue by Yuanye-F** [lenLRX/Atlas_ACL_E2E_Demo#18]
yolov3，yolov4，yolov3+deepsort已跑通流程，yolov5s转换om出错：

ATC start working now, please wait for a moment.
ATC run failed, Please check the detail log, Try 'atc --help' for more information
E89999: Inner Error!
        op[Concat_243], the input shape dims should be equal except merge axis,shapes:[[1, 3, 80, 80, 2, ], [1, 3, 40, 40, 81, ], ]axis:-1[FUNC:ConcatInferShapeCommon][FILE:split_combination_ops.cc][LINE:789]
        Call InferShapeAndType for node:Concat_243(ConcatD) failed[FUNC:Infer][FILE:infershape_pass.cc][LINE:117]
        process pass InferShapePass on node:Concat_243 failed, ret:4294967295[FUNC:RunPassesOnNode][FILE:base_pass.cc][LINE:492]
        build graph failed, graph id:0, [ret:1343242270[FUNC:BuildModel][FILE:ge_generator.cc][LINE:1378]

不修改 yolov5s.onnx 将focus层的slice和concate算子删除，可以转换成功，但是视频推理结果异常

**Comment by lenLRX** [comment]
你的yolov5是拉的yolov5作者最新的仓库吗？
如果是的话，可能是作者有修改，我要测试一下，可能需要我适配一下

**Comment by Yuanye-F** [comment]
前面一两个月拉下来的了，应该需要再做一下适配

**Comment by lenLRX** [comment]
我当时使用的是这个commit，我后续会同时适配两个版本
e96c74b5a1c4a27934c5d8ad52cde778af248ed8
https://github.com/ultralytics/yolov5/tree/e96c74b5a1c4a27934c5d8ad52cde778af248ed8

**Comment by lenLRX** [comment]
最新的yolov5 v6.0我已经适配了代码，你可以更新代码试一下
https://github.com/lenLRX/Atlas_ACL_E2E_Demo/blob/master/yolov5_model_cvt.md

**Comment by Yuanye-F** [comment]
好的，非常感谢，我再试试

**Comment by Yuanye-F** [comment]
使用新的代码转换和推理成功，再次感谢
