### ISSUE TITLE
使用自己的mp4文件，出现segmentation fault

### ISSUE THREAD

**Issue by C-SunRay** [lenLRX/Atlas_ACL_E2E_Demo#21]
您好，我用DN.mp4后出现了如图所示的错误，您知道如何解决吗？
![image](https://user-images.githubusercontent.com/57622222/155845888-f7a40444-ff61-4a77-8738-405ae3372c91.png)

**Comment by lenLRX** [comment]
yolov3的模型你放到model文件夹下面了吗
![image](https://user-images.githubusercontent.com/9995828/155845945-93056bc0-3513-4d64-88d8-06a0f8e577f3.png)

**Comment by C-SunRay** [comment]
……抱歉 菜的有些抠脚了
