### ISSUE TITLE
处理后的mp4全绿色

### ISSUE THREAD

**Issue by C-SunRay** [lenLRX/Atlas_ACL_E2E_Demo#22]
您好，使用yolov3-demo处理过后的视频全是绿色，请问您有见过这样的情况吗
![image](https://user-images.githubusercontent.com/57622222/155847058-e9dc55e0-7311-4e65-b80f-616636a44f1c.png)

**Comment by lenLRX** [comment]
你的软件版本是什么，驱动和CANN的版本

**Comment by C-SunRay** [comment]
CANN是5.0.2alpha003，驱动是Version=20.2.2

**Comment by lenLRX** [comment]
你这个是200DK还是200，看驱动好像是200加速模块？
如果可以的话尝试升级到最新版本的驱动和CANN再试试
这个版本我最近没有测试过，我之后会检查一下是什么问题

**Comment by C-SunRay** [comment]
应该是200加速模块，这个有大影响吗，我会尝试对其升级
