### ISSUE TITLE
需求：DeepSort部分C++部署

### ISSUE THREAD

**Issue by Yuanye-F** [lenLRX/Atlas_ACL_E2E_Demo#23]
能否跟踪部分使用C++部署，进一步提供跟踪性能

**Comment by lenLRX** [comment]
deepsort的tracker虽然是用python写的，实际上也是用numpy的接口，numpy都是C的实现。
不知道用C++能快多少，你有对比的数据吗。
我最近在看ByteTrack，看起来要快不少

**Comment by Yuanye-F** [comment]
![atlas_deepsort](https://user-images.githubusercontent.com/71813707/155941674-b0b141d8-1b04-48d0-b434-674be199c93b.jpg)

目前缺乏C++对比数据，从性能日志上分析 DeepSortTracker 部分用时较长

**Comment by lenLRX** [comment]
> ![atlas_deepsort](https://user-images.githubusercontent.com/71813707/155941674-b0b141d8-1b04-48d0-b434-674be199c93b.jpg)
> 
> 目前缺乏C++对比数据，从性能日志上分析 DeepSortTracker 部分用时较长

是的，这个性能我知道，达不到实时，如果有推荐的C++实现可以发一下链接，要我自己写一份C++的实现比较困难。
我最近测试一下ByteTrack的性能看看能不能达到实时吧，你一定要用deepsort吗

**Comment by Yuanye-F** [comment]
https://github.com/RichardoMrMu/yolov5-deepsort-tensorrt，这个是使用C++完成的Tracker部分

还不确定一定使用deepsort，只是一个目前比较好的选择

**Comment by lenLRX** [comment]
> [https://github.com/RichardoMrMu/yolov5-deepsort-tensorrt，这个是使用C++完成的Tracker部分](https://github.com/RichardoMrMu/yolov5-deepsort-tensorrt%EF%BC%8C%E8%BF%99%E4%B8%AA%E6%98%AF%E4%BD%BF%E7%94%A8C++%E5%AE%8C%E6%88%90%E7%9A%84Tracker%E9%83%A8%E5%88%86)
> 
> 还不确定一定使用deepsort，只是一个目前比较好的选择

ok，我找时间测试一下

**Comment by Yuanye-F** [comment]
好的，感谢

**Comment by lenLRX** [comment]
https://zhuanlan.zhihu.com/p/481008431

我在这个代码仓里面实现了ByteTrack的C++版本，你看一下能否满足你的需要？

**Comment by Yuanye-F** [comment]
好的，谢谢，我去测试一下结果。
