### ISSUE TITLE
您好 想向您请教这里使用的语法

### ISSUE THREAD

**Issue by C-SunRay** [lenLRX/Atlas_ACL_E2E_Demo#24]
我阅读了您的代码，我猜测这两处应该是有调用关系的，但不知道是什么语法支持了这一功能，我的C++并不熟练，故向您请教。
![image](https://user-images.githubusercontent.com/57622222/157060199-08e9b3ea-1538-4e72-a7c6-3a244b5b2a3a.png)
![image](https://user-images.githubusercontent.com/57622222/157060218-e79ee603-b17e-4568-9082-497286decfb9.png)

**Comment by C-SunRay** [comment]
我反应过来了，这个宏函数的写法我没有见过

**Comment by lenLRX** [comment]
这个宏的作用是在进程启动的时候将这个stream注册到StreamFactory, 利用的是全局静态变量初始化的原理
