### ISSUE TITLE
请问yolov5的aipp.cfg参数怎么得来能，可以解释一下参数吗？谢谢！

### ISSUE THREAD

**Issue by zoufangyu1987** [lenLRX/Atlas_ACL_E2E_Demo#25]
YOLOV3的aipp_yolov3_pp.cfg参数如下：

aipp_op {
aipp_mode : static
related_input_rank : 0
input_format : YUV420SP_U8
src_image_size_w : 416
src_image_size_h : 416
crop : false
csc_switch : true
rbuv_swap_switch : false
matrix_r0c0 : 256
matrix_r0c1 : 454
matrix_r0c2 : 0
matrix_r1c0 : 256
matrix_r1c1 : -88
matrix_r1c2 : -183
matrix_r2c0 : 256
matrix_r2c1 : 0
matrix_r2c2 : 359
input_bias_0 : 0
input_bias_1 : 128
input_bias_2 : 128
min_chn_0 : 104
min_chn_1 : 117
min_chn_2 : 123
var_reci_chn_0 : 0.0039216
var_reci_chn_1 : 0.0039216
var_reci_chn_2 : 0.0039216
}

YOLOV5的yuv420sp_aipp.cfg参数如下：
aipp_op {
aipp_mode: static
input_format : YUV420SP_U8
csc_switch : true
rbuv_swap_switch : false
matrix_r0c0 : 298
matrix_r0c1 : 0
matrix_r0c2 : 459
matrix_r1c0 : 298
matrix_r1c1 : -55
matrix_r1c2 : -136
matrix_r2c0 : 298
matrix_r2c1 : 541
matrix_r2c2 : 0
input_bias_0 : 16
input_bias_1 : 128
input_bias_2 : 128
var_reci_chn_0 : 0.0039216
var_reci_chn_1 : 0.0039216
var_reci_chn_2 : 0.0039216
}

查了其它资料，不太明白您YOLOV3和YOLOV5的参数差别很大。能解释一下这些参数怎么得来的吗？

**Comment by lenLRX** [comment]
yolov3的那个aipp我记得好像是官方教程里面的，后面的这个参数是官方文档里面给的
https://support.huaweicloud.com/atctool-cann51RC1alpha2/atlasatc_16_0023.html

![image](https://user-images.githubusercontent.com/9995828/158730047-44bf425f-ff0d-41ac-96f6-4990007c6966.png)

**Comment by lenLRX** [comment]
![image](https://user-images.githubusercontent.com/9995828/158730148-e5832c06-cf7e-4a2f-b52a-72b345859c09.png)
应该是这个，不过我觉得可能不会有很大的影响

**Comment by zoufangyu1987** [comment]
@lenLRX 清楚了，谢谢！
