### ISSUE TITLE
问题求助：./build.sh执行编译出现fatal error: acl/acl.h: No such file or directory

### ISSUE THREAD

**Issue by YING063** [lenLRX/Atlas_ACL_E2E_Demo#27]
准备运行demo案例，执行编译的时候，出现找不到acl头文件。检查环境变量是对的，请问可能是什么原因呢？

**Comment by lenLRX** [comment]
> 准备运行demo案例，执行编译的时候，出现找不到acl头文件。检查环境变量是对的，请问可能是什么原因呢？

应该是没有执行安装文档中的安装acllib这一步

**Comment by YING063** [comment]
> > 准备运行demo案例，执行编译的时候，出现找不到acl头文件。检查环境变量是对的，请问可能是什么原因呢？
> 
> 应该是没有执行安装文档中的安装acllib这一步

之前按照官方文档搭建了环境，安装了acllib。请问是需要重新安装一下再运行吗？

**Comment by lenLRX** [comment]
> > > 准备运行demo案例，执行编译的时候，出现找不到acl头文件。检查环境变量是对的，请问可能是什么原因呢？
> > 
> > 应该是没有执行安装文档中的安装acllib这一步
> 
> 之前按照官方文档搭建了环境，安装了acllib。请问是需要重新安装一下再运行吗？

我不知道官方文档做了什么，建议重新制卡，按照我的流程走。网速快的话大概15～30分钟吧
