### ISSUE TITLE
获取视频流输入出现的连接问题

### ISSUE THREAD

**Issue by YING063** [lenLRX/Atlas_ACL_E2E_Demo#28]
![图片5](https://user-images.githubusercontent.com/84767330/162185739-61e32b90-22e8-4fde-8a16-0769b9d9d2f5.png)

获取视频流输入，出现无法连接的问题，请问可能是哪里的原因呢？

**Comment by YING063** [comment]
200dk上ping不通






------------------ 原始邮件 ------------------
发件人: 李睿昕 ***@***.***&gt;
发送时间: 2022年4月7日 22:25
收件人: lenLRX/Atlas_ACL_E2E_Demo ***@***.***&gt;
抄送: YING063 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [lenLRX/Atlas_ACL_E2E_Demo] 获取视频流输入出现的连接问题 (Issue #28)





 
你在200DK上ping一下192.168.1.30看一下能不能ping通

**Comment by lenLRX** [comment]
> 200dk上ping不通
> 
> 
> 
> 
> 
> 
> ------------------ 原始邮件 ------------------
> 发件人: 李睿昕 ***@***.***&gt;
> 发送时间: 2022年4月7日 22:25
> 收件人: lenLRX/Atlas_ACL_E2E_Demo ***@***.***&gt;
> 抄送: YING063 ***@***.***&gt;, Author ***@***.***&gt;
> 主题: Re: [lenLRX/Atlas_ACL_E2E_Demo] 获取视频流输入出现的连接问题 (Issue #28)
> 
> 
> 
> 
> 
>  
> 你在200DK上ping一下192.168.1.30看一下能不能ping通
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

这就是你网络问题了
