### ISSUE TITLE
rtsp视频流输入丢包，无法执行检测程序

### ISSUE THREAD

**Issue by YING063** [lenLRX/Atlas_ACL_E2E_Demo#29]
输入设置为rtsp视频流，在执行./run.sh config/yolov3_demo.json时，出现丢包。
![图片6](https://user-images.githubusercontent.com/84767330/165067880-0d75af7f-b402-4563-a85c-dffa1d3e9c6b.png)

**Comment by YING063** [comment]
> 
拉流正常。
重新执行了一下，视频结果文件导出发现，不能正确框取目标（具体体现在无法框出人，却在空白处画框分类为人），会是什么哪个阶段的问题导致？

执行截图及profiling信息如下：
![图片7](https://user-images.githubusercontent.com/84767330/165276187-dd3f153d-95c9-48c4-b6a9-a558e9a5e932.png)
[perflog.10747.txt](https://github.com/lenLRX/Atlas_ACL_E2E_Demo/files/8562113/perflog.10747.txt)

**Comment by YING063** [comment]
换了根网线，检查了路由器，跑程序还是出现黄色max delay reached字样。如下图：
![图片8](https://user-images.githubusercontent.com/84767330/165497165-a2a654be-c4af-4fb5-9325-393fb950df15.png)
通过视频流播放器发现，视频会存在1~2秒延时，跟这个有关系吗？这个会是什么问题导致的呢？
profiling日志放在附件中了。
[perflog.2450.txt](https://github.com/lenLRX/Atlas_ACL_E2E_Demo/files/8571114/perflog.2450.txt)

然后关于检测精度，换了模型后，画框准确度提升了，不会存在在没有人的地方框出人的现象。感谢版主的解答。

**Comment by lenLRX** [comment]
1. 换网线的重点是换贵的网线，换超五类线或者六类线，当然也不一定是网页的问题
2. 1~2秒延时算不错了视频流延迟一般都不小
3. 可以尝试调低一些摄像头的码率，用播放器看一下视频流，确认一下码率是多少
