### ISSUE TITLE
想请教一下有关于YOLOv5 6.0 输出的问题

### ISSUE THREAD

**Issue by Gravekeeperx** [lenLRX/Atlas_ACL_E2E_Demo#30]
想请教一下您，如果想用样例输出标签应该如何修改代码呢

**Comment by lenLRX** [comment]
> 想请教一下您，如果想用样例输出标签应该如何修改代码呢

什么叫“样例输出标签”

**Comment by Gravekeeperx** [comment]
我想使用您的样例，输出检测出的目标的序号

**Comment by lenLRX** [comment]
> 我想使用您的样例，输出检测出的目标的序号

输出检测目标的序号需要有tracker，单独detection网络不行，除非视频只有一帧。

tracker网络参考bytetrack
