### ISSUE TITLE
想请问一下bytetrack追踪其他物体该如何训练

### ISSUE THREAD

**Issue by TANKCHENG** [lenLRX/Atlas_ACL_E2E_Demo#33]
使用检测其他种类如手机的yolox模型放入bytetrack中，但是效果不好，想问一下跟踪其他物体在bytetrack需要做什么调整吗？
谢谢！

**Comment by lenLRX** [comment]
检测精度的问题我没有办法回答。
除非原来在GPU上精度比较高，移植之后精度下降了很多，这种可以分析

**Comment by TANKCHENG** [comment]
自动回复：             已收到，谢谢来信
