### ISSUE TITLE
请问YOLOv5（6.0）进行ATC转换问题

### ISSUE THREAD

**Issue by HJS830** [lenLRX/Atlas_ACL_E2E_Demo#37]
作者你好，我导出onnx模型后，使用你提供的ATC命令进行转换，结果异常停止
log显示
   {
      "cause": [
        {
          "code": 1,
          "message": "The type is not supported."
        }
      ],
      "name": "Resize_117",
      "result": "failed",
      "type": "ai.onnx::13::Resize"
    },
我用Netron查看，应该是upsample那里有问题。请问你是否也遇到过类似的问题，以及如何解决呢？

**Comment by lenLRX** [comment]
ai.onnx::13::Resize

导出的时候我记得是要指定onnx 的opset为11，13可能不支持，不知道现在怎么样了
