### ISSUE TITLE
关于focus.cpp文件的几个问题

### ISSUE THREAD

**Issue by su-liechao** [lenLRX/Atlas_ACL_E2E_Demo#38]
您好，最近在学习您的这份把代码，有几个不太明白的地方
1.focus_op.cpp文件中的FocusTransformNEON，FocusTransformNEONFuse，CvtFocusNEONFuse这几个函数有什么区别吗？2.CvtFocusNEONFuse函数是不是包含了色彩空间转换和focus两个功能？Cvt转换得到的是rgb格式的吗，如果想得到bgr格式的该如何改进呢，NEON这部分代码还不太懂。

**Comment by lenLRX** [comment]
1. FocusTransformNEON只包含focus的功能，FocusTransformNEONFuse加上了对于像素值除255和转FP32的功能，CvtFocusNEONFuse在FocusTransformNEONFuse的基础上加上了YUV420SP转RGB的功能
2. 如果要修改像素顺序的话就修改这里面的RGB的顺序就行了https://github.com/lenLRX/Atlas_ACL_E2E_Demo/blob/master/src/focus_op.cpp#L426
