### ISSUE TITLE
关于检测代码中视频数据流的问题

### ISSUE THREAD

**Issue by su-liechao** [lenLRX/Atlas_ACL_E2E_Demo#40]
如果使用camera作为数据输入源，检测结果通过RTSP拉流显示，那么数据流是不是下面这个流程

camera输入(yuv420) -> yuv420sp2rgb -> npu推理+画框 -> dvpp编码 -> h264码流 -> 通过ffmpeg将码流写入到rtsp服务端 -> 本地vlc播放rtsp网络串流

1.通过ffmpeg将码流写入到rtsp服务端这一步理解的是不是有问题？
2.数据流程图中间是否有缺漏？

Thanks

**Comment by lenLRX** [comment]
我觉得没问题
