### ISSUE TITLE
YOLOX-ByteTrack的om模型使用

### ISSUE THREAD

**Issue by zhengpangzi** [lenLRX/Atlas_ACL_E2E_Demo#59]
你好，请问当我得到一个om模型之后，应该怎么使用ACL去使用该om模型，有相应示例吗，谢谢

**Comment by lenLRX** [comment]
如果你要用ACL自己开发的话，参考这个文件
https://github.com/lenLRX/Atlas_ACL_E2E_Demo/blob/master/src/acl_model.cpp
