### ISSUE TITLE
如何读取一个文件夹的图片作为输入

### ISSUE THREAD

**Issue by DayContorl** [lenLRX/Atlas_ACL_E2E_Demo#60]
已经成功实现了视频输入，想要改成识别一个文件夹内所有图片应该怎么做呢？请问当前的代码是否支持

**Comment by lenLRX** [comment]
当前代码不支持，要改流程，当前代码写死了是针对视频输入做的。图片使用的编解码器也不同(H264vsJPEG), 之前有打算支持图片，不过没做完就鸽了。。

**Comment by lenLRX** [comment]
如果是图片输入的话，当前这个程序的调用方式也不太好吧，给一个文件夹，期望输出一个文本作为结果？

**Comment by DayContorl** [comment]
希望输出一个对图片进行标注了的文件夹

**Comment by lenLRX** [comment]
> 希望输出一个对图片进行标注了的文件夹

这是可以实现的，不过短期内我不会继续开发
