### ISSUE TITLE
后处理时间过长，输出视频标注有点问题

### ISSUE THREAD

**Issue by RayAdas-GA-17** [lenLRX/Atlas_ACL_E2E_Demo#61]
![image](https://github.com/lenLRX/Atlas_ACL_E2E_Demo/assets/71073838/72708802-8763-4383-ae4e-44d028b1fcea)
![0c0a118e2fed27a2a91b5cf2a410c36](https://github.com/lenLRX/Atlas_ACL_E2E_Demo/assets/71073838/8d9f3537-8b0f-42ab-bb16-eeb284d47de2)

**Comment by RayAdas-GA-17** [comment]
![image](https://github.com/lenLRX/Atlas_ACL_E2E_Demo/assets/71073838/25381406-10d5-4eb1-810b-e00e79a9c968)
第一帧的后处理很长，后续帧的后处理在60ms左右

**Comment by lenLRX** [comment]
> ![image](https://user-images.githubusercontent.com/71073838/281727706-25381406-10d5-4eb1-810b-e00e79a9c968.png) 第一帧的后处理很长，后续帧的后处理在60ms左右

第一帧时间长，是因为初始化Python执行环境需要比较长的时间，后续处理60ms也有点长，不过应该取决于nms的对象数量，如果符合分数的框很多，确实可能很长。需要看看推理结果是否正确，是不是产生了过多虚假的结果

**Comment by lenLRX** [comment]
结合你给的图片，感觉问题是检测出了过多的错误结果，不过不太看得出来具体为什么错了。看起来你的测试用例有个比较特别的点是视频的高度只有277，我不清楚这会不会引起什么bug，我建议你使用一个标准的720P或者1080P的视频测试一下？如果确定是视频高度的问题，可以针对性的定位一下

**Comment by RayAdas-GA-17** [comment]
换了一个1280x720的视频，输出视频还是只有左上角有一堆文字

**Comment by RayAdas-GA-17** [comment]
![image](https://github.com/lenLRX/Atlas_ACL_E2E_Demo/assets/71073838/633ececb-4ac8-4b58-8b4e-2b73ce9e397e)
换了一个1280x720的视频，输出视频还是只有左上角有一堆文字
![image](https://github.com/lenLRX/Atlas_ACL_E2E_Demo/assets/71073838/4f378e7f-b02e-4903-af42-3da2cc8cb472)

**Comment by lenLRX** [comment]
https://github.com/lenLRX/Atlas_ACL_E2E_Demo/blob/master/yolov5_model_cvt.md#yolov5-v60

确认一下你用的yolov5的模型版本是不是这个v6.0的版本，因为看起来你这个模型的输出的shape和数量都不同。
你这里输出的shape是3个tensor。
当时这个程序适配的模型输出是一个tensor，shape是[batch, num_anchor, num_class+5] -> [1, 25220, 80+5] -> 8574800

如果你需要用其他版本的yolov5，可能需要重新适配一下后处理的代码

**Comment by RayAdas-GA-17** [comment]
确实是版本的问题，重新配置了一遍就正常了，非常感谢！
