### ISSUE TITLE
您好，请问如果想实现实时视频流输出是需要修改dst为网络地址吗

### ISSUE THREAD

**Issue by ouyang2055** [lenLRX/Atlas_ACL_E2E_Demo#68]
请问网络地址有什么要求吗直接使用rtsp://192.168.1.9:8554/tt1.mp4运行不起来
![image](https://github.com/lenLRX/Atlas_ACL_E2E_Demo/assets/168954467/39fabf78-4f8a-47a3-bdb6-aff6ad3d2a2a)
![image](https://github.com/lenLRX/Atlas_ACL_E2E_Demo/assets/168954467/2af50676-ce13-4ffa-8c10-e99c4aa60503)

**Comment by lenLRX** [comment]
https://zhuanlan.zhihu.com/p/464413201

**Comment by ouyang2055** [comment]
> https://zhuanlan.zhihu.com/p/464413201

谢谢！
