### ISSUE TITLE
运行报错：segmentation fault

### ISSUE THREAD

**Issue by Leon16226** [lenLRX/Atlas_ACL_E2E_Demo#8]
运行代码：
./run.sh config/yolov3_demo.json
报如下错误：
./run.sh: line 5:  1640 Segmentation fault      ./build/acl_demo_app -c $1

{
    "streams": [
        {
            "name": "deep_sort_demo_stream1",
            "stream_type": "deep_sort_demo",
            "src": "test.mp4",
            "dst": "output1.mp4",
            "hw_encoder": false,
            "yolov3_model_path": "./model/sample-yolov3_pp_416.om",
            "deepsort_model_path": "./model/deepsort_mars.om"
        }
    ],
    "config": {
        "app_perf": true,
        "perflog_path": "."
    }
}

**Comment by lenLRX** [comment]
请发一下程序输出的所有信息

**Comment by Leon16226** [comment]
可以了，因为没有安装环境的缘故。谢谢回复
